/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_businesstraining_HelloJNI */

#ifndef _Included_be_businesstraining_HelloJNI
#define _Included_be_businesstraining_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_businesstraining_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_be_businesstraining_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
